version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CICD_TEST
    overwrite: yes


permissions:
  - object: /
    pattern : "**"
    mode : 755
    owner : ec2-user
    group : ec2-user

hooks:
  ApplicationStart:
    - location: /home/ec2-user/CICD_TEST/start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: /home/ec2-user/CICD_TEST/stop.sh
      timeout: 300
      runas: ec2-user









