version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - sudo chmod 777 gradlew
      - ./gradlew build -x test
  build:
    commands:
      - echo "Build started on `date`"
      - ./gradlew clean build -x test
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Post-build steps"
      - ls build/libs/
      - echo "Build completed. Preparing to deploy."
artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - scripts/*
  discard-paths: yes

cache:
  paths:
    - ~/.gradle/caches/**

env:
  variables:
    DB_URL: "jdbc:mysql://your-database-url:3306/your-database-name"
    DB_USERNAME: "your-username"
    DB_PASSWORD: "your-password"

